name: pipeline
on:
  pull_request:

  push:
    branches:
      - master
    paths:
      - 'back-end/**'
      - 'front-end/**'
      - '.github/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Back-End
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Linting Tools
        run: pip install flake8 black

      - name: Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          workdir: 'back-end/'

      - name: Code Formatting
        run: black --check back-end/

      - name: Install Dependencies
        run: pip install -r back-end/requirements.txt

      - name: Install Test Dependencies
        run: pip install -r back-end/requirements_test.txt

      - name: Run Back-End Tests
        run: pytest -v back-end/test_app.py

  frontend:
    runs-on: ubuntu-latest
    name: Front-End
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Linting Tools
        run: pip install flake8 black

      - name: Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          workdir: 'front-end/'

      - name: Code Formatting
        run: black --check front-end/

      - name: Install Dependencies
        run: pip install -r front-end/requirements.txt

      - name: Install Front-End Test Dependencies
        run: pip install -r front-end/requirements_test.txt

      - name: Run Front-End Tests
        run: pytest -v front-end/test_app.py